version: '3.9'

services:

  config-server:
    image: config-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: config-server
    ports:
      - "9002:9002"