version: '3.9'

services:

  discovery-service:
    image: discovery-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: discovery-service
    ports:
      - "9001:9001"