version: '3.9'

services:

  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: gateway-service
    ports:
      - "9000:9000"