server:
  port: 0

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:9001/eureka/

ws:
  topic: /topic/mc1-mc2

timer:
  period: 10000

spring:

  sql:
    init:
      mode: embedded

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    defer-datasource-initialization: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/sessiondb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver