server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

ws:
  server: http://localhost:9000/websocket-service1/ws
  topic: /topic/mc1-mc2

spring:
  kafka:

    topic: message

    producer:
      bootstrap-servers: localhost:9092